### ISSUE TITLE
cannot open shared object file 

### ISSUE THREAD

**Issue by pinpuk** [buffer/pylibemu#13]
root@bt:~/Desktop/pylibemu-master# python setup.py build
running build
running build_ext
building 'pylibemu' extension
creating build
creating build/temp.linux-i686-2.6
creating build/temp.linux-i686-2.6/src
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/opt/libemu/include -I/usr/include/python2.6 -c src/pylibemu.c -o build/temp.linux-i686-2.6/src/pylibemu.o
creating build/lib.linux-i686-2.6
gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions build/temp.linux-i686-2.6/src/pylibemu.o -L/opt/libemu/lib -lemu -o build/lib.linux-i686-2.6/pylibemu.so
root@bt:~/Desktop/pylibemu-master# python setup.py install
running install
running build
running build_ext
running install_lib
copying build/lib.linux-i686-2.6/pylibemu.so -> /usr/local/lib/python2.6/dist-packages
running install_egg_info
Writing /usr/local/lib/python2.6/dist-packages/pylibemu-0.2.6.egg-info
root@bt:~/Desktop/pylibemu-master# python
Python 2.6.5 (r265:79063, Apr 16 2010, 13:09:56) 
[GCC 4.4.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylibemu
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libemu.so.2: cannot open shared object file: No such file or directory
>>> import pylibemu;
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: libemu.so.2: cannot open shared object file: No such file or directory
>>>

**Comment by buffer** [comment]
Please execute (as root)

touch /etc/ld.so.conf.d/libemu.conf
echo "/opt/libemu/lib/" > /etc/ld.so.conf.d/libemu.conf
ldconfig
