### ISSUE TITLE
problems with setup.py

### ISSUE THREAD

**Issue by shibumi** [buffer/pylibemu#22]
Hello,
I have problems with setup.py.. what am I doing wrong?

```
running install
running build
running build_clib
running 'autoreconf -v -i -f' for library 'emu'
autoreconf: 'configure.ac' or 'configure.in' is required
```

**Comment by buffer** [comment]
Are you sure you cloned the repo recursively?

`git clone --recursive https://github.com/buffer/pylibemu.git`

**Comment by shibumi** [comment]
Hello @buffer 
Wait.. so you ship libemu within your repository? the thing is that I want to package pylibemu for the AUR.. and I ship already libemu. So I just want to install pylibemu above it. Is this possible?

**Comment by buffer** [comment]
The simplest thing you can do is to not clone recursively, copy your own libemu in the submodules tree and run 

```
python setup.py build
sudo python setup.py install
```

in the pylibemu directory. The alternative is to modify setup.py.

**Comment by shibumi** [comment]
Copying libemu into the submodules tree is impossible for me because I build every package in a clean Chroot. I don't think that I will modify the setup.py. Sorry, I will drop the package in the AUR.
