### ISSUE TITLE
Error trying to install, same error using pip and manual install

### ISSUE THREAD

**Issue by sparrowd** [buffer/pylibemu#23]
Hello,

I am trying to install the program and have tried both pip install pylibemu and also using the files recursively grabbed from git and I am getting the following error and could use some help. 

Package libemu was not found in the pkg-config search path.
    Perhaps you should add the directory containing `libemu.pc'
    to the PKG_CONFIG_PATH environment variable
    No package 'libemu' found

Now I have looked for the file libemu.pc and I cannot seem to find it in this git. Can anyone assist me?

**Comment by buffer** [comment]
The file libemu.pc is not contained in the libemu tree but it is generated by pkg-config. This is a strange error. Which distro are you using?

**Comment by sparrowd** [comment]
This is on RHEL 7

**Comment by komajp** [comment]
I'm in the same situation. 

`Package libemu was not found in the pkg-config search path.
Perhaps you should add the directory containing `libemu.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libemu' found`

`[root@localhost pylibemu]# locate libemu.pc
/root/chopshop/chopshop-master/pylibemu/build/temp.linux-x86_64-2.7/emu/libemu.pc
/root/chopshop/chopshop-master/pylibemu/build/temp.linux-x86_64-2.7/emu/libemu.pc.in
/root/chopshop/chopshop-master/pylibemu/submodules/libemu/libemu.pc.in
/usr/lib/pkgconfig/libemu.pc
[root@localhost pylibemu]# pkg-config --exists --print-errors libemu ; echo $?
0`

**Comment by DjCalvin** [comment]
Having the same issue on centos 7. Both pip and git.

Package libemu was not found in the pkg-config search path.
Perhaps you should add the directory containing `libemu.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libemu' found

**Comment by buffer** [comment]
> Needed to install libemu-devel in order to get around the PKG_CONFIG_PATH issue on Centos 7

Thanks for the useful hint!
